language: node_js

node_js:
  - 10
  - 12

os:
  - linux
  - osx

branches:
  only:
    - master
    - develop

notifications:
  email: false

script:
  - yarn global add codecov
  - yarn run lint
  - yarn run build
  - yarn run build:dev
  - yarn run build:prod
  - yarn test

after_success:
  - codecov
