version: "{build}"

environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 12

branches:
  only:
    - master
    - develop

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

before_test:
  - node --version
  - yarn --version

test_script:
  - yarn run lint
  - yarn run build
  - yarn run build:dev
  - yarn run build:prod
  - yarn test

build: off

deploy: off
