name: dependencies-status

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: 0 8 5,15,25 * *

jobs:
  dependencies-status:
    name: Dependencies Status
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: sudo yarn global add npm-check
      - run: yarn install --production
      - run: npm-check --production --skip-unused
